agent {
    data_dir = "/run/spire/data"
    log_level = "DEBUG"
    server_address = "127.0.0.1"
    server_port = "8081"
    socket_path = "/run/spire/sockets/agent.sock"
    trust_domain = "mpx.sovereign"
    insecure_bootstrap = false
    trust_bundle_path = "/run/spire/bootstrap.crt"
    join_token = "REDACTED_SPIRE_TOKEN_2"    # emergency re-attestation only; rotated 2026-03-13
}

health_checks {
    listener_enabled = true
    bind_address = "127.0.0.1"
    bind_port = "8082"
    live_path = "/live"
    ready_path = "/ready"
}

plugins {
    NodeAttestor "join_token" {
        plugin_data {}
    }

    KeyManager "disk" {
        plugin_data {
            directory = "/run/spire/data"
        }
    }

    WorkloadAttestor "docker" {
        plugin_data {
            docker_socket_path = "unix:///var/run/docker.sock"
        }
    }
}
