"""
PDF security report generator for KITT.

Generates a board-ready security report after a demo run:
  - Posture score with breakdown
  - Detection summary (by category, severity)
  - Per-attack timeline
  - Model response comparison for flagged prompts

Uses fpdf2 for zero-dependency PDF generation.
"""

import io
from datetime import datetime, timezone
from typing import Optional

try:
    from fpdf import FPDF
    PDF_AVAILABLE = True
except ImportError:
    PDF_AVAILABLE = False


def is_available() -> bool:
    """Check if PDF generation is available (fpdf2 installed)."""
    return PDF_AVAILABLE


def generate_report(events: list[dict], posture: dict,
                    title: str = "KITT Security Assessment") -> Optional[bytes]:
    """
    Generate a PDF security report from event data.
    Returns PDF bytes or None if fpdf2 is not installed.
    """
    if not PDF_AVAILABLE:
        return None

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 12, title, new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, "KITT Sovereign Gateway - MadProjX", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    # Posture Score
    score = posture.get("score", 0)
    rating = posture.get("rating", "Unknown")
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, f"Security Posture Score: {score}/100 ({rating})", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # Score breakdown
    breakdown = posture.get("breakdown", {})
    max_values = {"layers_active": 40, "detection_rate": 30, "accuracy": 20, "identity": 10}
    pdf.set_font("Helvetica", "", 10)
    for key, val in breakdown.items():
        label = key.replace("_", " ").title()
        max_val = max_values.get(key, "?")
        pdf.cell(0, 6, f"  {label}: {val}/{max_val}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # Detection Summary
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Detection Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)

    total = len(events)
    warnings = len([e for e in events if e.get("severity") == "warning"])
    criticals = len([e for e in events if e.get("severity") == "critical"])
    info = total - warnings - criticals

    pdf.cell(0, 6, f"  Total events: {total}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"  Warnings: {warnings}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"  Critical: {criticals}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"  Informational: {info}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # Events by layer
    by_layer = {}
    for e in events:
        layer = e.get("layer", "unknown")
        by_layer[layer] = by_layer.get(layer, 0) + 1

    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Events by Security Layer", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    for layer, count in sorted(by_layer.items()):
        pdf.cell(0, 6, f"  {layer}: {count}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # Flagged events detail
    flagged = [e for e in events if e.get("severity") in ("warning", "critical")]
    if flagged:
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "Flagged Events", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        for e in flagged[:30]:
            ts = e.get("ts", "")[:19]
            layer = e.get("layer", "")
            etype = e.get("type", "")
            severity = e.get("severity", "")
            details = e.get("details", {})
            detail_str = ", ".join(f"{k}={v}" for k, v in details.items()) if isinstance(details, dict) else str(details)
            line = f"  [{ts}] {severity.upper()} | {layer}/{etype} | {detail_str[:80]}"
            pdf.cell(0, 5, _sanitize(line), new_x="LMARGIN", new_y="NEXT")

    # Footer
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 5, "This report was generated by KITT Sovereign Gateway. All data remains on-premises.", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, "No security telemetry was transmitted to external services during this assessment.", new_x="LMARGIN", new_y="NEXT")

    buf = io.BytesIO()
    pdf.output(buf)
    return buf.getvalue()


def _sanitize(text: str) -> str:
    """Replace non-latin-1 characters for PDF core font compatibility."""
    return text.encode("latin-1", errors="replace").decode("latin-1")
